Repository fuzzylabs/matcha, pull requests merged in 2023-07, with the labels that each got.

#162 [RPD-267] Fix `pyyaml` version conflict
  poetry.lock
  pyproject.toml
Labels: bug

#163 [RPD-268] Fix spelling issues
  .pre-commit-config.yaml
  RELEASE_NOTES.md
Labels: bug

#165 [RPD-261] [BUG] destroy leads to missing matcha config file error
  src/matcha_ml/core/core.py
  src/matcha_ml/state/remote_state_manager.py
  tests/test_state/test_remote_state_manager.py
Labels: bug

#166 [RPD-272] Updates to documentation
  docs/azure-permissions.md
  docs/getting-started.md
Labels: documentation

#168 [RPD-276] [BUG] Turning analytics `on` causes hanging in the analytics service
  src/matcha_ml/services/analytics_service.py
  tests/conftest.py
Labels: bug

#167 [RPD-271] [BUG] Fix orphaned `NetworkWatcherRG` resource group
  docs/getting-started.md
  docs/inside-matcha.md
Labels: bug, documentation

#170 [RPD-279] [BUG] Automatically deal with stale states
  src/matcha_ml/infrastructure/remote_state_storage/output.tf
  src/matcha_ml/state/matcha_state.py
  src/matcha_ml/templates/azure_template.py
Labels: bug

#172 RPD-280 remove RESOURCE_NAMES from azure_runner
  src/matcha_ml/runners/azure_runner.py
Labels: improvement

#171 [RPD-205] add data versioning terraform files to infrastructure
  src/matcha_ml/infrastructure/resources/data_version_control_storage/README.md
  src/matcha_ml/infrastructure/resources/data_version_control_storage/main.tf
  src/matcha_ml/infrastructure/resources/data_version_control_storage/output.tf
  src/matcha_ml/infrastructure/resources/data_version_control_storage/providers.tf
  src/matcha_ml/infrastructure/resources/data_version_control_storage/variables.tf
  src/matcha_ml/infrastructure/resources/main.tf
  src/matcha_ml/infrastructure/resources/output.tf
Labels: enhancement

#174 [RPD-206] update provisioning code to include data versioning resource
  src/matcha_ml/infrastructure/resources/main.tf
  src/matcha_ml/infrastructure/resources/output.tf
  src/matcha_ml/runners/azure_runner.py
  src/matcha_ml/state/matcha_state.py
  src/matcha_ml/templates/azure_template.py
Labels: enhancement

#173 [RPD-273] Improvements to the `provision` user experience
  .pre-commit-config.yaml
  .typos.toml
  docs/azure-permissions.md
  docs/references.md
  pyproject.toml
  src/matcha_ml/cli/constants.py
  src/matcha_ml/cli/ui/spinner.py
  src/matcha_ml/cli/ui/status_message_builders.py
  src/matcha_ml/errors.py
  src/matcha_ml/runners/base_runner.py
  src/matcha_ml/runners/remote_state_runner.py
  src/matcha_ml/services/analytics_service.py
  src/matcha_ml/services/terraform_service.py
  tests/test_runners/test_base_runner.py
  tests/test_services/test_terraform_service.py
Labels: enhancement

#177 [RPD-274] [BUG] Fix inaccurate provisioning messages
  src/matcha_ml/runners/azure_runner.py
  src/matcha_ml/runners/base_runner.py
  src/matcha_ml/runners/remote_state_runner.py
  tests/test_runners/test_base_runner.py
Labels: bug

#178 [RPD-263] add inference of zenml version from environment
  src/matcha_ml/core/core.py
Labels: enhancement

#169 Bug Fixes July-2023
  .pre-commit-config.yaml
  .typos.toml
  docs/azure-permissions.md
  docs/getting-started.md
  docs/inside-matcha.md
  docs/references.md
  pyproject.toml
  src/matcha_ml/cli/constants.py
  src/matcha_ml/cli/ui/spinner.py
  src/matcha_ml/cli/ui/status_message_builders.py
  src/matcha_ml/core/core.py
  src/matcha_ml/errors.py
  src/matcha_ml/infrastructure/remote_state_storage/output.tf
  src/matcha_ml/runners/azure_runner.py
  src/matcha_ml/runners/base_runner.py
  src/matcha_ml/runners/remote_state_runner.py
  src/matcha_ml/services/analytics_service.py
  src/matcha_ml/services/terraform_service.py
  src/matcha_ml/state/matcha_state.py
  src/matcha_ml/state/remote_state_manager.py
  src/matcha_ml/templates/azure_template.py
  tests/conftest.py
  tests/test_runners/test_base_runner.py
  tests/test_services/test_terraform_service.py
  tests/test_state/test_remote_state_manager.py
Labels: bug, documentation

#176 [RPD-190] feature/data-version-control
  docs/data-version-control.md
  docs/getting-started.md
  docs/img/inside-matcha/matcha-under-the-hood.png
  mkdocs.yml
  src/matcha_ml/infrastructure/resources/data_version_control_storage/README.md
  src/matcha_ml/infrastructure/resources/data_version_control_storage/main.tf
  src/matcha_ml/infrastructure/resources/data_version_control_storage/output.tf
  src/matcha_ml/infrastructure/resources/data_version_control_storage/providers.tf
  src/matcha_ml/infrastructure/resources/data_version_control_storage/variables.tf
  src/matcha_ml/infrastructure/resources/main.tf
  src/matcha_ml/infrastructure/resources/output.tf
  src/matcha_ml/state/matcha_state.py
  src/matcha_ml/templates/azure_template.py
Labels: documentation, enhancement
