Repository fuzzylabs/matcha, pull requests merged in 2023-06, with the labels that each got.

#134 [RPD-231] Improvements to `provision` and `destroy` logging
  src/matcha_ml/cli/cli.py
  src/matcha_ml/cli/constants.py
  src/matcha_ml/cli/destroy.py
  src/matcha_ml/cli/provision.py
  src/matcha_ml/runners/azure_runner.py
  src/matcha_ml/runners/base_runner.py
  src/matcha_ml/state/remote_state_manager.py
  tests/test_runners/test_azure_runner.py
  tests/test_runners/test_base_runner.py
  tests/test_state/test_remote_state_manager.py
Labels: improvement

#136 [RPD-237] Add a check for the user and environment uuid
  src/matcha_ml/services/_validation.py
  src/matcha_ml/services/analytics_service.py
  src/matcha_ml/services/global_parameters_service.py
  tests/test_services/__init__.py
  tests/test_services/conftest.py
  tests/test_services/test_analytics_service.py
  tests/test_services/test_global_parameters_service.py
  tests/test_services/test_validation.py
Labels: improvement

#135 [RPD-234] [BUG] Handle existing matcha configuration better
  src/matcha_ml/cli/provision.py
  src/matcha_ml/state/remote_state_manager.py
  tests/test_cli/test_provision.py
  tests/test_state/test_remote_state_manager.py
Labels: bug

#137 [RPD-226] Download `.matcha` from remote state storage if state file hash mismatch state when `matcha get` command is run
  src/matcha_ml/cli/cli.py
  src/matcha_ml/core/core.py
  src/matcha_ml/state/matcha_state.py
  src/matcha_ml/state/remote_state_manager.py
  src/matcha_ml/storage/azure_storage.py
  tests/test_cli/test_get.py
  tests/test_core/test_core.py
  tests/test_state/test_matcha_state.py
Labels: enhancement

#139 [RPD-233] Change the matcha-ml global variable config location from a users home folder
  src/matcha_ml/services/global_parameters_service.py
  tests/test_services/test_global_parameters_service.py
Labels: improvement

#138 [RPD-238] [BUG] Stop matcha.lock file from being created in the users local directory
  src/matcha_ml/constants.py
  src/matcha_ml/state/remote_state_manager.py
  src/matcha_ml/storage/azure_storage.py
  tests/test_storage/test_azure_storage.py
Labels: bug

#140 [RPD-240] `matcha destroy` command does not work in remote scenraio
  src/matcha_ml/cli/cli.py
  src/matcha_ml/runners/azure_runner.py
  src/matcha_ml/runners/remote_state_runner.py
  src/matcha_ml/services/terraform_service.py
  tests/test_runners/test_azure_runner.py
  tests/test_runners/test_remote_state_runner.py
  tests/test_services/test_terraform_service.py
Labels: bug

#141 [RPD-242] Consolidate `matcha destroy` and `matcha destroy full` into one command
  src/matcha_ml/cli/cli.py
  src/matcha_ml/cli/destroy.py
  src/matcha_ml/cli/provision.py
  src/matcha_ml/core/core.py
  src/matcha_ml/runners/azure_runner.py
  src/matcha_ml/runners/base_runner.py
  src/matcha_ml/state/remote_state_manager.py
  src/matcha_ml/templates/azure_template.py
  tests/test_cli/test_destroy.py
  tests/test_cli/test_get.py
  tests/test_cli/test_provision.py
  tests/test_core/test_core.py
  tests/test_services/test_analytics_service.py
  tests/test_templates/test_azure_template.py
Labels: improvement

#145 [RPD-244] Add CI to feature branches
  .github/workflows/ci.yml
Labels: enhancement

#143 [RPD-191] Add an init to core to enable a cleaner import
  src/matcha_ml/cli/cli.py
  src/matcha_ml/core/__init__.py
  tests/test_cli/test_analytics.py
  tests/test_cli/test_force_unlock.py
  tests/test_core/test_core.py
Labels: enhancement

#144 [RPD-195] Add _validation to core
  src/matcha_ml/cli/_validation.py
  src/matcha_ml/cli/destroy.py
  src/matcha_ml/constants.py
  src/matcha_ml/core/_validation.py
  src/matcha_ml/state/matcha_state.py
  tests/conftest.py
  tests/test_cli/test_destroy.py
  tests/test_cli/test_get.py
  tests/test_cli/test_provision.py
  tests/test_cli/test_validation.py
  tests/test_core/test_core.py
  tests/test_core/test_core_validation.py
  tests/test_runners/test_azure_runner.py
  tests/test_state/test_matcha_state.py
  tests/test_state/test_remote_state_manager.py
Labels: enhancement

#147 [RPD-193] Refactor `TemplateRunner.is_approved` into a UI function
  src/matcha_ml/cli/destroy.py
  src/matcha_ml/cli/provision.py
  src/matcha_ml/cli/ui/user_approval_functions.py
  src/matcha_ml/runners/azure_runner.py
  tests/test_cli/test_ui_functions.py
  tests/test_runners/test_azure_runner.py
Labels: improvement

#150 [RPD-192] Create a `destroy` function in core
  src/matcha_ml/cli/cli.py
  src/matcha_ml/core/__init__.py
  src/matcha_ml/core/core.py
  src/matcha_ml/state/remote_state_manager.py
  tests/test_cli/test_cli.py
  tests/test_cli/test_destroy.py
  tests/test_cli/test_get.py
  tests/test_core/test_core.py
  tests/test_core/test_core_destroy.py
  tests/test_core/test_core_validation.py
  tests/test_services/test_analytics_service.py
  tests/test_state/test_remote_state_manager.py
Labels: enhancement

#152 [RPD-253] transform user input to lower case on get command
  src/matcha_ml/core/core.py
  tests/test_core/test_core.py
Labels: enhancement

#155 [RPD-196] add api reference documentation to the website
  .github/workflows/docs.yml
  docs/references.md
  mkdocs.yml
  poetry.lock
  pyproject.toml
Labels: documentation

#148 [RPD-245] Update documentation with state sharing and removal of `matcha destroy full`
  docs/getting-started.md
  docs/img/getting-started/shared-state.png
Labels: documentation

#153 [RPD-247] Move the creation of state from `AzureRunner` into `MatchaStateService`
  src/matcha_ml/runners/azure_runner.py
  src/matcha_ml/runners/base_runner.py
  src/matcha_ml/services/terraform_service.py
  src/matcha_ml/state/matcha_state.py
  src/matcha_ml/state/remote_state_manager.py
  src/matcha_ml/templates/azure_template.py
  tests/conftest.py
  tests/test_cli/test_provision.py
  tests/test_core/test_core.py
  tests/test_core/test_core_provision.py
  tests/test_runners/test_azure_runner.py
  tests/test_services/conftest.py
  tests/test_state/conftest.py
  tests/test_state/test_matcha_state.py
  tests/test_state/test_remote_state_manager.py
Labels: enhancement

#159 [BUG] [RPD-258] Instantiate MatchStateService after downloading the matcha state from the remote storage
  src/matcha_ml/core/core.py
  tests/test_core/test_core.py
Labels: bug

#154 [RPD-254] no state file after destroying resources
  src/matcha_ml/services/analytics_service.py
Labels: bug

#160 [BUG] [RPD-257] Stop removal of contents of "matcha/infrastructure/remote_state_storage" during `matcha provision`
  src/matcha_ml/core/core.py
  src/matcha_ml/runners/azure_runner.py
  src/matcha_ml/state/matcha_state.py
  tests/test_cli/test_provision.py
  tests/test_runners/test_azure_runner.py
  tests/test_state/test_matcha_state.py
Labels: bug
