Repository fuzzylabs/matcha, pull requests merged in 2023-08, with the labels that each got.

#183 [RPD-288] Update CI to run on PR from gitflow notation branches
  .github/workflows/ci.yml
Labels: improvement

#180 [RPD-287] ZenML version inference for zenserver
  .github/workflows/ci.yml
  src/matcha_ml/core/core.py
  src/matcha_ml/infrastructure/resources/.terraform.lock.hcl
  src/matcha_ml/infrastructure/resources/main.tf
  src/matcha_ml/infrastructure/resources/variables.tf
  src/matcha_ml/infrastructure/resources/zen_server/main.tf
  src/matcha_ml/infrastructure/resources/zen_server/variables.tf
  src/matcha_ml/infrastructure/resources/zen_server/zenml_helm/Chart.yaml
  src/matcha_ml/infrastructure/resources/zen_server/zenml_helm/templates/server-deployment.yaml
  src/matcha_ml/infrastructure/resources/zen_server/zenml_helm/templates/server-ingress.yaml
  src/matcha_ml/infrastructure/resources/zen_server/zenml_helm/values.yaml
  tests/test_cli/test_provision.py
  tests/test_core/test_core_provision.py
Labels: enhancement

#184 [RPD-260] Add an object to handle the `matcha.config.json` file.
  poetry.lock
  src/matcha_ml/config/__init__.py
  src/matcha_ml/config/matcha_config.py
  src/matcha_ml/core/core.py
  src/matcha_ml/state/remote_state_manager.py
  tests/conftest.py
  tests/test_config/test_matcha_config.py
  tests/test_state/test_remote_state_manager.py
Labels: improvement

#181 [RPD-249] Refactor `analytics_service` to simplify tracking decorator
  docs/data-version-control.md
  docs/getting-started.md
  src/matcha_ml/infrastructure/resources/data_version_control_storage/output.tf
  src/matcha_ml/infrastructure/resources/output.tf
  src/matcha_ml/infrastructure/resources/zen_server/zenml_helm/values.yaml
  src/matcha_ml/services/analytics_service.py
  src/matcha_ml/state/__init__.py
  tests/conftest.py
  tests/test_cli/test_provision.py
  tests/test_core/test_core_provision.py
  tests/test_services/test_analytics_service.py
Labels: improvement

#186 [RPD-236] Improved approach to check ignored folder when uploading and downloading
  src/matcha_ml/storage/azure_storage.py
Labels: improvement

#185 [RPD-283] add core function for updating stack type
  .github/workflows/ci.yml
  poetry.lock
  src/matcha_ml/cli/cli.py
  src/matcha_ml/config/__init__.py
  src/matcha_ml/config/matcha_config.py
  src/matcha_ml/core/core.py
  src/matcha_ml/infrastructure/resources/.terraform.lock.hcl
  src/matcha_ml/infrastructure/resources/main.tf
  src/matcha_ml/infrastructure/resources/variables.tf
  src/matcha_ml/infrastructure/resources/zen_server/main.tf
  src/matcha_ml/infrastructure/resources/zen_server/variables.tf
  src/matcha_ml/infrastructure/resources/zen_server/zenml_helm/Chart.yaml
  src/matcha_ml/infrastructure/resources/zen_server/zenml_helm/templates/server-deployment.yaml
  src/matcha_ml/infrastructure/resources/zen_server/zenml_helm/templates/server-ingress.yaml
  src/matcha_ml/infrastructure/resources/zen_server/zenml_helm/values.yaml
  src/matcha_ml/state/remote_state_manager.py
  tests/conftest.py
  tests/test_cli/test_provision.py
  tests/test_cli/test_stack.py
  tests/test_config/test_matcha_config.py
  tests/test_core/test_core_provision.py
  tests/test_core/test_stack_set.py
  tests/test_state/test_remote_state_manager.py
Labels: enhancement

#188 [RPD-250] Move `_show_terraform_outputs()` into `provision`
  src/matcha_ml/core/core.py
  src/matcha_ml/runners/azure_runner.py
  src/matcha_ml/runners/base_runner.py
  tests/test_cli/conftest.py
  tests/test_core/conftest.py
  tests/test_core/test_core_provision.py
  tests/test_runners/test_azure_runner.py
Labels: improvement

#189 [RPD-286] Add documentation on "stacks" and the new LLM stack
  docs/resource-stacks.md
  mkdocs.yml
Labels: documentation

#190 [RPD-259] Refactor `build_state_from_terraform_output` within `matcha_state.py` to use objects defined within matcha_state.py
  src/matcha_ml/services/analytics_service.py
  src/matcha_ml/state/matcha_state.py
  tests/test_state/test_matcha_state.py
Labels: improvement

#194 [RPD-289] Update the Chroma Terraform within the LLM stack to use Helm
  src/matcha_ml/infrastructure/llm/chroma/README.md
  src/matcha_ml/infrastructure/llm/chroma/chroma_helm/Chart.yaml
  src/matcha_ml/infrastructure/llm/chroma/chroma_helm/templates/deployment.yaml
  src/matcha_ml/infrastructure/llm/chroma/chroma_helm/templates/pvc.yaml
  src/matcha_ml/infrastructure/llm/chroma/chroma_helm/templates/service.yaml
  src/matcha_ml/infrastructure/llm/chroma/chroma_helm/values.yaml
  src/matcha_ml/infrastructure/llm/chroma/main.tf
  src/matcha_ml/templates/azure_template.py
Labels: enhancement

#195 [RPD-292] [BUG] Update AzureTemplate to not create redundant folders during provisioning
  src/matcha_ml/core/core.py
  src/matcha_ml/templates/azure_template.py
  tests/test_cli/test_provision.py
  tests/test_core/test_core_provision.py
Labels: bug

#196 [RPD-303] Update `stack_set` docstring to include example and raises
  src/matcha_ml/core/core.py
Labels: enhancement

#193 [RPD-278] Bug Fixes and Improvements
  .pre-commit-config.yaml
  docs/data-version-control.md
  docs/getting-started.md
  src/matcha_ml/config/matcha_config.py
  src/matcha_ml/core/core.py
  src/matcha_ml/infrastructure/llm/main.tf
  src/matcha_ml/infrastructure/llm/variables.tf
  src/matcha_ml/infrastructure/llm/zen_server/main.tf
  src/matcha_ml/infrastructure/llm/zen_server/variables.tf
  src/matcha_ml/infrastructure/llm/zen_server/zenml_helm/Chart.yaml
  src/matcha_ml/infrastructure/llm/zen_server/zenml_helm/templates/server-deployment.yaml
  src/matcha_ml/infrastructure/llm/zen_server/zenml_helm/templates/server-ingress.yaml
  src/matcha_ml/infrastructure/llm/zen_server/zenml_helm/values.yaml
  src/matcha_ml/runners/azure_runner.py
  src/matcha_ml/runners/base_runner.py
  src/matcha_ml/services/analytics_service.py
  src/matcha_ml/state/__init__.py
  src/matcha_ml/state/matcha_state.py
  src/matcha_ml/state/remote_state_manager.py
  src/matcha_ml/storage/azure_storage.py
  tests/conftest.py
  tests/test_cli/conftest.py
  tests/test_config/test_matcha_config.py
  tests/test_core/conftest.py
  tests/test_core/test_core_provision.py
  tests/test_runners/test_azure_runner.py
  tests/test_services/test_analytics_service.py
  tests/test_state/test_matcha_state.py
  tests/test_state/test_remote_state_manager.py
Labels: bug

#199 [RPD-248] Add a basic example demonstrating how to use the API
  docs/getting-started.md
Labels: documentation

#201 [RPD-305] fix circular import error
  src/matcha_ml/runners/base_runner.py
  tests/test_runners/test_base_runner.py
Labels: bug

#204 [RPD-299] Create CLI stack remove command
  RELEASE_NOTES.md
  docs/getting-started.md
  pyproject.toml
  src/matcha_ml/VERSION
  src/matcha_ml/cli/_validation.py
  src/matcha_ml/cli/cli.py
  src/matcha_ml/core/__init__.py
  src/matcha_ml/core/core.py
  src/matcha_ml/runners/base_runner.py
  tests/test_cli/test_stack.py
  tests/test_runners/test_base_runner.py
Labels: enhancement

#206 [RPD-308] Add stack module validation
  src/matcha_ml/core/_validation.py
  tests/test_core/test_core_validation.py
Labels: enhancement

#207 [RPD-310] Update MatchaConfig and MatchaConfigComponent to include adding and removal of properties without overwriting
  src/matcha_ml/config/matcha_config.py
  tests/test_config/test_matcha_config.py
Labels: enhancement

#208 [RPD-306] Add core stack add command
  poetry.lock
  pyproject.toml
  src/matcha_ml/cli/cli.py
  src/matcha_ml/config/matcha_config.py
  src/matcha_ml/constants.py
  src/matcha_ml/core/_validation.py
  src/matcha_ml/core/core.py
  tests/test_cli/test_stack.py
  tests/test_core/test_core.py
  tests/test_core/test_core_validation.py
Labels: enhancement

#211 [RPD-307] add core stack remove command
  src/matcha_ml/cli/cli.py
  src/matcha_ml/config/matcha_config.py
  src/matcha_ml/core/core.py
  tests/conftest.py
  tests/test_cli/test_stack.py
  tests/test_config/test_matcha_config.py
  tests/test_core/test_core.py
  tests/test_core/test_stack_set.py
Labels: enhancement

#209 [RPD-312] Update base_template/azure_template files to handle new modular Terraform files
  src/matcha_ml/core/core.py
  src/matcha_ml/templates/azure_template.py
  tests/test_templates/test_azure_template.py
Labels: enhancement
