Repository fuzzylabs/matcha, pull requests merged in 2023-05, with the labels that each got.

#79 [RPD-136] Publish documentation website
  .github/workflows/docs.yml
Labels: enhancement

#80 [RPD-138] Update matcha repo readme with links to documentation
  README.md
  docs/index.md
Labels: documentation

#81 [RPD-140] Downgrade pyyaml package
  poetry.lock
  pyproject.toml
Labels: bug

#83 [RPD-141] Update the documentation link for matcha cli
  src/matcha_ml/cli/cli.py
Labels: documentation, improvement

#87 [RPD-170] Update version information
  pyproject.toml
  src/matcha_ml/VERSION
Labels: improvement

#82 [RPD-132] Move `matcha provision` existing deployment validations to the start of the command
  src/matcha_ml/cli/_validation.py
  src/matcha_ml/cli/cli.py
  src/matcha_ml/cli/provision.py
Labels: bug, enhancement

#86 [RPD-167] `provision` fails when run on the machine which has never done anything k8s related
  .github/workflows/docs.yml
  src/matcha_ml/services/terraform_service.py
  src/matcha_ml/templates/run_template.py
  tests/test_services/test_terraform_service.py
Labels: bug

#85 [RPD-162] Improve the repository readme
  README.md
Labels: documentation

#88 [RPD-171] unable to destroy when provision fails part way through
  src/matcha_ml/cli/_validation.py
  src/matcha_ml/cli/cli.py
  src/matcha_ml/cli/destroy.py
  src/matcha_ml/infrastructure/main.tf
  src/matcha_ml/templates/build_templates/azure_template.py
  src/matcha_ml/templates/run_template.py
  tests/test_cli/test_provision.py
  tests/test_templates/test_azure_template.py
  tests/test_templates/test_run_template.py
Labels: bug

#90 [RPD-162] Improve the repository readmes
  README.md
  docs/img/matcha-provision.gif
Labels: documentation

#97 [RPD-177] Add attribution to terraform files
  src/matcha_ml/infrastructure/configure_kubectl.tf
  src/matcha_ml/infrastructure/kubernetes.tf
  src/matcha_ml/infrastructure/mlflow_module/getURI.tf
  src/matcha_ml/infrastructure/mlflow_module/main.tf
  src/matcha_ml/infrastructure/mlflow_module/providers.tf
  src/matcha_ml/infrastructure/seldon/istio.tf
  src/matcha_ml/infrastructure/seldon/main.tf
  src/matcha_ml/infrastructure/seldon/outputs.tf
  src/matcha_ml/infrastructure/seldon/providers.tf
  src/matcha_ml/infrastructure/seldon/variables.tf
  src/matcha_ml/infrastructure/zen_server/main.tf
Labels: improvement

#99 [BUG] [RPD-179] Add `pymdown-extensions` as a dependency to solve security issue
  poetry.lock
  pyproject.toml
Labels: bug, documentation

#96 [RPD-172] Improve documentation
  README.md
  docs/azure-permissions.md
  docs/costings.md
  docs/css/extra.css
  docs/getting-started.md
  docs/img/favicon.png
  docs/img/getting-started/recommendation-example-mlflow.png
  docs/img/logo.png
  docs/img/matcha-provision.gif
  docs/img/stack-diagram.png
  docs/index.md
  docs/inside-matcha.md
  docs/workflows.md
  mkdocs.yml
Labels: documentation

#89 [RPD-169] Add unique identifier or ID to a state file
  src/matcha_ml/templates/run_template.py
  tests/test_templates/test_run_template.py
Labels: enhancement

#93 [RPD-158] Add functionality for creating a unique user identifier
  poetry.lock
  pyproject.toml
  src/matcha_ml/services/global_parameters_service.py
  tests/test_services/test_global_parameters_service.py
Labels: enhancement

#92 [RPD-168] Add command for opting out of usage data collection
  src/matcha_ml/cli/analytics.py
  src/matcha_ml/cli/cli.py
  src/matcha_ml/services/global_parameters_service.py
  tests/test_cli/test_analytics.py
  tests/test_services/test_global_parameters_service.py
Labels: enhancement

#104 [RPD-181] Update README with raw links to images
  README.md
Labels: documentation

#105 [RPD-173] Correct test docstrings
  tests/test_services/test_global_parameters_service.py
  tests/test_services/test_matcha_state.py
Labels: documentation

#91 [RPD-174] Remote State Manager
  poetry.lock
  pyproject.toml
  src/matcha_ml/core/core.py
  src/matcha_ml/state/__init__.py
  src/matcha_ml/state/matcha_state.py
  src/matcha_ml/state/remote_state_manager.py
  src/matcha_ml/storage/__init__.py
  src/matcha_ml/storage/azure_storage.py
  src/matcha_ml/templates/build_templates/azure_template.py
  tests/conftest.py
  tests/test_state/test_matcha_state.py
Labels: improvement

#109 [RPD-185] Update the version number and release notes
  RELEASE_NOTES.md
  poetry.lock
  pyproject.toml
  src/matcha_ml/VERSION
Labels: improvement

#108 [RPD-121] Improve testing for _check_required_role_assignments
  src/matcha_ml/services/azure_service.py
  tests/conftest.py
  tests/test_services/test_azure_service.py
Labels: improvement

#98 [RPD-151] Add documentation on analytics
  docs/inside-matcha.md
  docs/privacy.md
  mkdocs.yml
Labels: documentation

#110 [RPD-182] Refactor analytics opt-out/in into core
  src/matcha_ml/cli/analytics.py
  src/matcha_ml/cli/cli.py
  src/matcha_ml/core/core.py
  tests/test_cli/test_analytics.py
  tests/test_core/test_core.py
Labels: improvement

#106 [RPD-164] Check whether remote state bucket has been provisioned
  src/matcha_ml/cli/cli.py
  src/matcha_ml/cli/destroy.py
  src/matcha_ml/cli/provision.py
  src/matcha_ml/state/remote_state_manager.py
  src/matcha_ml/storage/azure_storage.py
  tests/test_cli/test_destroy.py
  tests/test_cli/test_get.py
  tests/test_state/test_remote_state_manager.py
  tests/test_storage/test_azure_storage.py
Labels: enhancement

#101 [RPD-144] Save the state to the provisioned bucket, when `provision` or `destroy` are finished
  poetry.lock
  pyproject.toml
  src/matcha_ml/cli/cli.py
  src/matcha_ml/services/azure_service.py
  src/matcha_ml/state/remote_state_manager.py
  src/matcha_ml/storage/azure_storage.py
  tests/conftest.py
  tests/test_services/test_azure_service.py
  tests/test_state/test_remote_state_manager.py
  tests/test_storage/test_azure_storage.py
Labels: enhancement

#115 [RPD-216] Update Requests package
  poetry.lock
  pyproject.toml
Labels: bug

#117 [RPD-217] Update github action workflows to run against `develop` branch
  .github/workflows/ci.yml
  .github/workflows/docs.yml
Labels: bug

#112 [RPD-210] [BUG] Fix breaking of documentation link
  CNAME
  docs/css/extra.css
  docs/img/logo-white.png
  docs/privacy.md
  mkdocs.yml
Labels: bug

#122 [RPD-146] Lock and unlock remote state
  src/matcha_ml/cli/cli.py
  src/matcha_ml/cli/destroy.py
  src/matcha_ml/cli/provision.py
  src/matcha_ml/cli/ui/status_message_builders.py
  src/matcha_ml/state/remote_state_manager.py
  src/matcha_ml/storage/azure_storage.py
  tests/test_cli/test_destroy.py
  tests/test_cli/test_get.py
  tests/test_cli/test_provision.py
  tests/test_state/test_remote_state_manager.py
  tests/test_storage/test_azure_storage.py
Labels: enhancement

#127 [RPD-145] Get the state before `provision` or `destroy` command is run
  src/matcha_ml/cli/destroy.py
  src/matcha_ml/cli/provision.py
  src/matcha_ml/state/remote_state_manager.py
  src/matcha_ml/storage/azure_storage.py
  tests/test_cli/test_provision.py
  tests/test_state/test_remote_state_manager.py
Labels: enhancement

#116 [RPD-147] Add command to force unlock
  src/matcha_ml/cli/cli.py
  src/matcha_ml/core/__init__.py
  src/matcha_ml/core/core.py
  src/matcha_ml/state/remote_state_manager.py
  src/matcha_ml/storage/azure_storage.py
  tests/test_cli/test_force_unlock.py
  tests/test_core/test_core.py
Labels: enhancement

#120 [RPD-214] Update documentation for remote state storage ticket
  docs/getting-started.md
  docs/img/azure-permissions/azure-cost-breakdown.png
  docs/inside-matcha.md
Labels: documentation

#123 [RPD-221] Remote state upload and download should respect file deletion
  src/matcha_ml/storage/azure_storage.py
  tests/test_storage/test_azure_storage.py
Labels: enhancement

#129 [RPD-215] [BUG] `matcha provision` fails running multiple times
  src/matcha_ml/cli/_validation.py
  src/matcha_ml/services/azure_service.py
  src/matcha_ml/state/remote_state_manager.py
  src/matcha_ml/storage/azure_storage.py
  tests/test_services/test_azure_service.py
  tests/test_state/test_remote_state_manager.py
  tests/test_storage/test_azure_storage.py
Labels: bug

#132 [RPD-229] [BUG] `download_folder` function tries to delete entire directory
  src/matcha_ml/storage/azure_storage.py
  tests/test_storage/test_azure_storage.py
Labels: bug
